
CREATE TABLE `myTable` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `Name` varchar(255) default NULL,
  `Email` varchar(255) default NULL,
  `City` varchar(255),
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `myTable` (`Id`,`Name`,`Email`,`City`) VALUES (1,"Hector Barnes","Class.aptent@pharetra.org","Durness"),(2,"Cadman Grant","bibendum@estarcuac.com","Bathurst"),(3,"Igor Cannon","tellus@utmi.net","Vihari"),(4,"Fletcher Stephenson","id@semutcursus.com","Augusta"),(5,"Ulric Fuller","amet.risus@DonecestNunc.co.uk","Huntsville"),(6,"Kareem Mack","tellus@iaculisaliquetdiam.co.uk","Vichte"),(7,"Jasper Velasquez","nec.orci.Donec@interdumenim.com","Marcedusa"),(8,"Linus Miller","tristique.senectus.et@tellusNunc.ca","Puerto Montt"),(9,"Kadeem Gallagher","enim.nisl.elementum@eratneque.co.uk","Açailândia"),(10,"Kenneth Gibson","nonummy.ipsum@augueeu.com","Connah's Quay");
INSERT INTO `myTable` (`Id`,`Name`,`Email`,`City`) VALUES (11,"Kelly Meyers","Quisque.porttitor@semperrutrumFusce.net","Beerst"),(12,"Ira Whitley","vitae@convallis.net","Runcorn"),(13,"Troy Melendez","ac@Phasellusvitae.net","Swan Hills"),(14,"Aidan Patel","Fusce@primisinfaucibus.co.uk","Bredene"),(15,"Damian Armstrong","interdum.Sed@enimnislelementum.ca","Minto"),(16,"Aristotle Knight","interdum@Nam.co.uk","Göteborg"),(17,"Quentin Pate","quis.turpis@euismodin.edu","Tirúa"),(18,"Logan Johns","Curabitur@Fusce.co.uk","Vizianagaram"),(19,"Nasim Dalton","sodales.elit.erat@mauris.co.uk","Schiltigheim"),(20,"Amos Boyle","pharetra.felis@leoMorbineque.com","Chaumont-Gistoux");
INSERT INTO `myTable` (`Id`,`Name`,`Email`,`City`) VALUES (21,"Chester Huff","elit@lobortis.net","Tintange"),(22,"Murphy Lucas","nisi.sem.semper@commodotincidunt.ca","Calvera"),(23,"Donovan Hood","ipsum@erosturpisnon.ca","Bury St. Edmunds"),(24,"Jerry Jarvis","tincidunt.neque.vitae@SeddictumProin.com","Palmerston North"),(25,"Jared Gilmore","Lorem.ipsum.dolor@nonloremvitae.net","Clearwater Municipal District"),(26,"Steel Davidson","enim@conubia.net","Koblenz"),(27,"Kirk Herring","purus.accumsan@bibendum.org","Panquehue"),(28,"Oscar York","arcu.eu.odio@suscipit.co.uk","St. Thomas"),(29,"Harlan Boyle","pellentesque@inmolestie.ca","Salisbury"),(30,"Nash Parker","nunc.Quisque@milaciniamattis.net","Sambreville");
INSERT INTO `myTable` (`Id`,`Name`,`Email`,`City`) VALUES (31,"Trevor Bond","tellus@nullaanteiaculis.ca","Drongen"),(32,"Hasad Sosa","vel.sapien.imperdiet@tellusPhaselluselit.edu","Hornsea"),(33,"Brady Cantu","eget@mus.net","New Westminster"),(34,"Rajah Acevedo","enim.nisl.elementum@felisadipiscing.edu","Ophain-Bois-Seigneur-Isaac"),(35,"Brock Cardenas","pede@malesuadaIntegerid.ca","Ofena"),(36,"Upton Weeks","in.consectetuer.ipsum@antelectus.edu","Thon"),(37,"Callum Stokes","nunc.sed@Phasellusfermentumconvallis.co.uk","Santomenna"),(38,"Zachery Serrano","Nulla.facilisi.Sed@risusNunc.com","Río Negro"),(39,"Hu Dickson","massa@a.net","Kirkland"),(40,"Igor Sanders","Donec.egestas.Duis@vehiculaPellentesquetincidunt.net","Langen");
INSERT INTO `myTable` (`Id`,`Name`,`Email`,`City`) VALUES (41,"Jordan Maldonado","ipsum@dapibusid.com","Alva"),(42,"Vaughan Wade","In.tincidunt@Inscelerisque.com","Saalfelden am Steinernen Meer"),(43,"Cameron Myers","ipsum.Suspendisse@Namligula.net","Trowbridge"),(44,"Jermaine Oconnor","Nullam.lobortis@lacusUt.org","Sherbrooke"),(45,"Caleb Odom","et.malesuada@mollisIntegertincidunt.ca","Ghislarengo"),(46,"Hector English","diam.nunc.ullamcorper@auctorodio.co.uk","Lidingo"),(47,"Cooper Clayton","Donec.fringilla.Donec@accumsanneque.com","Gangtok"),(48,"Patrick Yates","quis.arcu.vel@arcu.com","Cherbourg-Octeville"),(49,"Ralph Matthews","Nunc.ac.sem@Namnulla.ca","Maunath Bhanjan"),(50,"Quinn Leonard","est.ac.facilisis@musAenean.co.uk","Glendon");
INSERT INTO `myTable` (`Id`,`Name`,`Email`,`City`) VALUES (51,"Aidan Hurst","ultrices@lacusQuisqueimperdiet.com","Lozzo Atestino"),(52,"Ryder Green","Duis@nonummyultricies.co.uk","Lennik"),(53,"Abdul Shaffer","Suspendisse.non.leo@adipiscinglobortis.co.uk","Rivière-du-Loup"),(54,"Anthony Mcpherson","mollis@tellusAenean.co.uk","Pollena Trocchia"),(55,"Lawrence Guzman","risus@Nulladignissim.org","Beauport"),(56,"Stephen Donovan","dolor@quamafelis.com","Port Alice"),(57,"Martin Preston","pharetra@Praesenteudui.ca","Landau"),(58,"Fitzgerald Long","nascetur.ridiculus@mattissemperdui.net","Pilibhit"),(59,"Herman Parks","fames@fermentum.co.uk","Meerhout"),(60,"Robert Cortez","orci@volutpat.org","Whitburn");
INSERT INTO `myTable` (`Id`,`Name`,`Email`,`City`) VALUES (61,"Matthew Mayer","Proin.dolor@lobortisquama.net","Bedollo"),(62,"Felix Dillon","scelerisque.dui.Suspendisse@nuncnullavulputate.org","Spalbeek"),(63,"Raymond Carson","non.magna@Curabiturmassa.org","Alix"),(64,"Melvin Kidd","litora@luctus.ca","Rae Lakes"),(65,"Phelan Keith","et@sedleoCras.edu","Casalvieri"),(66,"Price Odonnell","elementum.dui@quamafelis.co.uk","Llangefni"),(67,"Edan Dale","massa.Suspendisse@facilisis.edu","Pau"),(68,"Noah Dalton","in.magna.Phasellus@magnaLoremipsum.com","Pollena Trocchia"),(69,"Todd Barker","nec.euismod@necluctusfelis.ca","Butte"),(70,"Elmo Chan","pharetra.sed.hendrerit@musAeneaneget.net","Morwell");
INSERT INTO `myTable` (`Id`,`Name`,`Email`,`City`) VALUES (71,"Nolan Velazquez","cursus.Nunc@vitaedolor.edu","Wemmel"),(72,"Perry Harrison","pharetra.sed.hendrerit@massa.org","Neuruppin"),(73,"Donovan Rosales","consectetuer@milacinia.ca","Timaukel"),(74,"Yuli Charles","Sed.auctor.odio@ametluctusvulputate.co.uk","Genappe"),(75,"Galvin Booth","sapien@dolor.net","Bassiano"),(76,"Ray Shields","nulla@CurabiturmassaVestibulum.co.uk","Vieste"),(77,"Callum Hoffman","ligula@orci.org","Pichilemu"),(78,"Tobias Owen","Donec.est@Nam.edu","Teruel"),(79,"Prescott Gonzalez","velit.dui@facilisisnon.org","Kitchener"),(80,"Perry Solomon","neque.Nullam.ut@inhendrerit.com","Bertiolo");
INSERT INTO `myTable` (`Id`,`Name`,`Email`,`City`) VALUES (81,"Erasmus Rowland","parturient@Etiamligula.org","Rochester"),(82,"Nicholas Pierce","ornare.lectus.ante@orcilobortis.net","Nasino"),(83,"Lamar Boyer","vestibulum.Mauris.magna@Nuncmauris.ca","Burcht"),(84,"Nero Mann","nibh.Aliquam.ornare@volutpatornare.net","Malderen"),(85,"Alfonso Peck","metus.eu.erat@nisi.net","St. Andrä"),(86,"George Craft","magnis.dis@quam.com","Spittal an der Drau"),(87,"Brock Salas","semper.erat@ut.ca","Dokkum"),(88,"Camden Mann","lacinia.Sed.congue@a.co.uk","Chambave"),(89,"Kasimir Farley","ridiculus.mus@magna.com","Alès"),(90,"Beck Mckinney","mauris@tortorNunccommodo.com","Ortonovo");
INSERT INTO `myTable` (`Id`,`Name`,`Email`,`City`) VALUES (91,"Owen Mcpherson","Nunc.lectus.pede@Aliquam.com","Alexandra"),(92,"Addison Winters","enim.condimentum@inlobortis.net","Purén"),(93,"Joel Washington","a@purusac.net","Valkenburg aan de Geul"),(94,"Guy Sherman","ante.ipsum.primis@eusemPellentesque.ca","Vertou"),(95,"Davis Moses","vestibulum@eusemPellentesque.ca","Yahyalı"),(96,"Reese Frederick","Nunc@egestasDuisac.edu","Darmstadt"),(97,"Aristotle Goodwin","egestas.Duis.ac@Classaptenttaciti.ca","Redcliffe"),(98,"Malik Stein","libero@accumsan.org","San José de Maipo"),(99,"Thor Heath","et.risus@acmattis.org","Malahide"),(100,"Adrian Blankenship","aliquet@ridiculus.net","Eckville");
